services:
  backend:
    image: eclipse-temurin:25-jdk

    working_dir: /app

    volumes:
      - .:/app
      - maven-cache:/root/.m2

    env_file:
      - .env

    ports:
      - "8080:8080"

    command: ./mvnw spring-boot:run

volumes:
  maven-cache:
